// ==UserScript==
// @name         Autohide Missions
// @namespace    http://tampermonkey.net/
// @version      1.5.2
// @description  Autohides missions that don't need your attention. Added settings and set default settings to do nothing.
// @author       MisteryKid
// @include      /^https?:\/\/[www.]*(?:leitstellenspiel\.de|missionchief\.co\.uk|missionchief\.com|meldkamerspel\.com|centro-de-mando\.es|missionchief-australia\.com|larmcentralen-spelet\.se|operatorratunkowy\.pl|operatore112\.it|operateur112\.fr|dispetcher112\.ru|alarmcentral-spil\.dk|nodsentralspillet\.com|operacni-stredisko\.cz|112-merkez\.com|jogo-operador112\.com|operador193\.com|centro-de-mando\.mx|dyspetcher101-game\.com|missionchief-japan\.com|hatakeskuspeli\.com|missionchief-korea\.com|jocdispecerat112\.com|dispecerske-centrum\.com)\/.*$/
// @require      https://openuserjs.org/src/libs/sizzle/GM_config.js
// @grant        none
// ==/UserScript==


(function(){function g(b,c,e){var f=b.children;b.style.display="";f[1].style.display="";var a=b.classList;a.contains("mission_panel_red")?h(d,b,f):a.contains("mission_panel_yellow")?h(e,b,f):a.contains("mission_panel_green")&&(classList=b.classList,classList.contains("panel-success")?h(d,b,f):h(c,b,f))}function h(b,c,e){switch(b){case a:c.style.display="";e[1].style.display="";break;case d:c.style.display="";e[1].style.display="none";break;case k:c.style.display="none",e[1].style.display="none"}}
function l(){for(var b=$(".missionSideBarEntry"),c=0;c<b.length;c++){var e=b[c].getAttribute("mission_id"),a=JSON.parse(localStorage.getItem("lssm_missionOut"));null==a?g(b[c].firstElementChild,GM_config.get("greenStatus"),GM_config.get("yellowStatus")):a.hasOwnProperty(e)||g(b[c].firstElementChild,GM_config.get("greenStatus"),GM_config.get("yellowStatus"))}}if("nl_NL"==I18n.locale){var m="Meldingen verbergen";var n="Groene Status";var p="Gele Status";var k="Verbergen";var d="Inklappen";var a="Niets doen";
var q="Opslaan";var r="Sluiten";var t="Reset naar standaard"}else m="Auto Hide Missions",n="Green Status",p="Yellow Status",k="Hidden",d="Collapse",a="Nothing",q="Save",r="Close",t="Reset to default";var u=document.createElement("div");$("#search_input_field_missions").before(u);GM_config.init({id:"autoHideMissions",title:m,fields:{greenStatus:{label:n,type:"select","default":a,options:[k,d,a]},yellowStatus:{label:p,type:"select","default":a,options:[k,d,a]}},css:"#autoHideMissions_greenStatus_var { background-image: linear-gradient(to bottom, #5cb85c 0, #419641 100%); text-align: center; height: 30px; line-height: 30px;border-radius: 10px; border: 0px solid #000; padding: 0px;} #autoHideMissions_yellowStatus_var { background-image: linear-gradient(to bottom, #f0d54e 0, #f0ad4e 100%);  text-align: center; height: 30px; line-height: 30px; border-radius: 10px; border: 0px solid #000; padding: 0px;} #autoHideMissions_field_yellowStatus { color: #000; } #autoHideMissions_field_greenStatus { color: #000; }",
events:{open:function(){GM_config.frame.setAttribute("style","border-radius: 10px; border: 2px solid #000; padding: 20px; height: auto; background: #666;")},save:function(){l();GM_config.close("autoHideMissions")}},frame:u});l();$("#btn-group-mission-select").append('<a id="autoHideMissionsSettings" class="btn btn-xs btn-success mission_selection" title="autoHideMissions Settings"><div class="glyphicon glyphicon-cog"></div></a>');$("#autoHideMissionsSettings").on("click",function(b){GM_config.open("autoHideMissions");
document.getElementById("autoHideMissions_saveBtn").firstChild.data=q;document.getElementById("autoHideMissions_closeBtn").firstChild.data=r;document.getElementById("autoHideMissions_resetLink").firstChild.data=t});var v=missionMarkerAdd;missionMarkerAdd=function(b){v.apply(this,arguments);for(var c=$(".missionSideBarEntry"),a=0;a<c.length;a++){var f=c[a].getAttribute("mission_id"),d=JSON.parse(localStorage.getItem("lssm_missionOut"));null==d?g(c[a].firstElementChild,GM_config.get("greenStatus"),
GM_config.get("yellowStatus")):d.hasOwnProperty(f)||g(c[a].firstElementChild,GM_config.get("greenStatus"),GM_config.get("yellowStatus"))}}})();